#!/usr/bin/env python3
"""Offline verification gates for dependency security, API documentation, and archived docs.

Run from the repository root:

    python scripts/check_verification_gates.py
    python scripts/check_verification_gates.py --only api-doc

Gates
-----
lockfile   Dependency security floors plus manifest/lock agreement. Prevents the
           advisories closed for fastmcp (CVE-2026-32871) and fast-uri
           (CVE-2026-13676) from silently regressing on a future lock refresh.
api-doc    Every action the mod accepts in POST /action must appear in the
           action contract block in docs/api.md, and the block must not list
           actions the code no longer supports.
api-facts  Facts that docs/api.md states and that code owns must still agree:
           the documented `mod_version` against mod_manifest.json, the screen
           enum against the screens GameStateService.ResolveNonModalScreen can
           emit, the documented default port against HttpServer.DefaultPort, and
           the /state payload surface against the docs/api.md tables that
           describe it. Sixteen payload records are checked field-for-field
           against their own table, every action_readiness reason code
           EvaluateCombatActionGate can answer with must be documented, the
           compact agent_view rename table must match the renames the
           BuildAgent*Payload methods actually perform, and under all of it sits
           a coarse net: every serialized field of every /state payload record
           has to be named somewhere in docs/api.md.
           The action contract only covers action names, so all of this would
           otherwise drift silently -- which is what happened. 91 fields across
           23 records had shipped with no mention anywhere a client could read,
           including whole screens an agent has to drive (character_select,
           multiplayer_lobby, game_over) and the session block the play skill
           tells agents to route on first.
api-schema Generated `docs/openapi.json` must byte-match the standard-library generator,
           which extracts ordinary HTTP routes and C# wire payload records and takes shared
           vocabularies (actions, errors, screens, SSE events) from existing contracts.
doc-marks  Date-stamped validation records must carry a historical marker, and
           archived topic pages must keep their redirect to history/.
docs-tracked
           Every Markdown page under docs/ must be tracked by git. docs/ used to
           be gitignored, so a new page could be written, pass the local
           doc-marks gate, and still be missing from every fresh checkout --
           which is what CI builds from.
packaged-links
           Every local link in a packaged document (README.md, README.zh-CN.md,
           mcp_server/README.md) must resolve inside the release artifact. The
           relative ones are rewritten to absolute URLs by the hand-kept table in
           package-release.ps1, so a newly added relative link could ship
           unrewritten and only fail the artifact check after packaging.
script-encoding
           PowerShell scripts containing non-ASCII text must carry a UTF-8 BOM.
ps1-syntax Every PowerShell script under scripts/ must parse without a syntax error.
           Each one is a build, packaging, validation, or CI entry point that nothing
           else compiles, so a stray brace or quote would only surface when a release
           or a real-machine run finally invoked it. Parsing goes through the
           PowerShell AST parser, which reads a script without executing it. Skips
           with a note when scripts/ holds no .ps1 or no interpreter is on PATH.

Exit code 0 means every selected gate passed. Exit code 1 means at least one
gate failed and the failure detail has been printed to stderr. Standard library
only: preflight invokes this with the system Python.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

# --- Gate configuration -----------------------------------------------------

# Minimum safe versions. Each entry names the advisory it protects against.
SECURITY_FLOORS: dict[str, tuple[str, str]] = {
    # package -> (minimum safe version, advisory)
    "fastmcp": ("3.2.0", "CVE-2026-32871 (issue #50)"),
    "fast-uri": ("3.1.6", "CVE-2026-13676 (issue #51)"),
}

# Locks are regenerated by tooling; these overrides must survive a refresh.
REQUIRED_NPM_OVERRIDES = {"yauzl": "3.2.1"}

# Files that must exist for the targets below to mean anything. Deliberately tracked
# files only: AGENTS.md is gitignored and therefore absent from a fresh checkout, which
# is exactly the environment CI runs the gates in.
ROOT_SENTINELS = ("STS2AIAgent/mod_manifest.json", "mcp_server/pyproject.toml")

API_CONTRACT_BEGIN = "<!-- BEGIN ACTION CONTRACT -->"
API_CONTRACT_END = "<!-- END ACTION CONTRACT -->"

# --- api-facts sources of truth --------------------------------------------

# The health example claims a mod version; docs/api.md itself says the value tracks the
# mod, so the manifest is the thing it has to agree with.
MOD_VERSION_PATTERN = re.compile(r'"mod_version"\s*:\s*"([^"]+)"')
MANIFEST_VERSION_PATH = "STS2AIAgent/mod_manifest.json"

# The "## Screen 枚举" table is the client-facing screen vocabulary.
SCREEN_SECTION_HEADING = "## Screen 枚举"
DOC_SCREEN_ROW = re.compile(r"^\|\s*\`([A-Z][A-Z0-9_]*)\`", re.MULTILINE)

# GameStateService.ResolveNonModalScreen is the single producer of these names: early
# guards `return "X";`, then the switch expression's `=> "X"` arms.
RESOLVE_SCREEN_SIGNATURE = "private static string ResolveNonModalScreen(IScreenContext? currentScreen)"
CODE_SCREEN_SWITCH_ARM = re.compile(r'=>\s*"([A-Z][A-Z0-9_]*)"')
CODE_SCREEN_EARLY_RETURN = re.compile(r'return\s+"([A-Z][A-Z0-9_]*)"')
# A near-total parse failure (renamed method, rewritten in another style) must fail loudly
# instead of silently reading as "no screens to check".
MIN_CODE_SCREENS = 20

CODE_DEFAULT_PORT = re.compile(r"private\s+const\s+int\s+DefaultPort\s*=\s*(\d+)\s*;")
DOC_DEFAULT_PORT = re.compile(r"默认[^\n]*127\.0\.0\.1:(\d+)")
HTTP_SERVER_PATH = "STS2AIAgent/Server/HttpServer.cs"

# The /state combat payload is the surface an agent reads before every decision, and it is also
# the one that has drifted: `action_readiness`, `players[]`, `end_turn_will_kill_player` and
# `lethal_risks[]` all shipped and reached the compact agent_view while docs/api.md documented
# none of them. The action contract covers action names only, so nothing noticed. These two C#
# records are the producers; the docs/api.md tables below are what clients are told to expect.
GAME_STATE_PATH = "STS2AIAgent/Game/GameStateService.cs"
# GameStateService is one partial class across several files. The raw payload records and the screen
# resolver live in the file above; the compact agent_view rewrite was split out on 2026-09-17, and
# the raw /state builders by screen on 2026-09-20. A check reads whichever file owns what it asks
# about, and each one fails loudly when its extraction comes back empty.
#
# Two checks below ask a question about the *class* rather than about one of its files -- which
# reason codes the combat gate can emit, and which screens the resolver can report. Reading either
# from a single path worked only until the member moved, which is exactly how this gate went red
# when the builders were split. They read the whole family instead.
AGENT_VIEW_PATH = "STS2AIAgent/Game/GameStateService.AgentView.cs"
PAYLOADS_PATH = "STS2AIAgent/Game/GameStateService.Payloads.cs"
GAME_STATE_CLASS_GLOB = "GameStateService*.cs"
# The leading @ is C#'s escape for a keyword used as an identifier -- `public EventPayload? @event`
# serializes as "event". Missing it would read as "the docs list a field the code does not have".
CSHARP_PAYLOAD_PROPERTY = re.compile(
    r"^\s*public\s+[^\s].*?\s@?([a-z][a-z0-9_]*)\s*\{\s*get;\s*init;", re.MULTILINE
)
DOC_FIELD_ROW = re.compile(r"^\|\s*\`([a-z][a-z0-9_]*)\`\s*\|", re.MULTILINE)
COMBAT_PAYLOAD_TABLES = (
    ("internal sealed class CombatPayload", "#### `combat` 顶层字段"),
    ("internal sealed class CombatActionReadinessPayload", "#### `combat.action_readiness`"),
    ("internal sealed class CombatLethalRiskPayload", "#### `combat.lethal_risks[]`"),
    ("internal sealed class GameStatePayload", "### 顶层字段"),
    ("internal sealed class SessionPayload", "### `session` 子结构"),
    ("internal sealed class MultiplayerPayload", "### `multiplayer` 子结构"),
    ("internal sealed class MultiplayerLobbyPayload", "### `multiplayer_lobby` 子结构"),
    ("internal sealed class CharacterSelectPayload", "### `character_select` 子结构"),
    ("internal sealed class CharacterSelectOptionPayload", "#### `character_select.characters[]`"),
    ("internal sealed class CharacterSelectPlayerPayload", "#### `character_select.players[]`"),
    ("internal sealed class TimelinePayload", "### `timeline` 子结构"),
    ("internal sealed class TimelineSlotPayload", "#### `timeline.slots[]`"),
    ("internal sealed class UnlockPayload", "### `unlock` 子结构"),
    ("internal sealed class ModalPayload", "### `modal` 子结构"),
    ("internal sealed class GameOverPayload", "### `game_over` 子结构"),
    ("internal sealed class MapPlayerVotePayload", "#### `map.player_votes[]`"),
)

# Every reason the gate can answer with has to be spelled out for clients, because each one tells
# an agent something different about whether to wait, to clear a modal, or to stop asking. The
# producer is one method, so the list cannot be assembled from anywhere else.
COMBAT_GATE_SIGNATURE = (
    "private static CombatActionGate EvaluateCombatActionGate(IScreenContext? currentScreen, "
    "CombatState? combatState)"
)
CODE_GATE_REASON = re.compile(r'reason\s*=\s*"([a-z][a-z0-9_]*)"')
DOC_REASON_SECTION = "#### `combat.action_readiness`"
MIN_GATE_REASONS = 15

STATE_PAYLOAD_RECORD = re.compile(r"internal sealed class (\w*Payload)\b")
DOC_FENCE = re.compile(r"```.*?```", re.DOTALL)
DOC_INLINE_CODE = re.compile(r"`([^`\n]+)`")
# A near-total parse failure must fail loudly rather than read as "nothing to check".
MIN_STATE_PAYLOAD_RECORDS = 40

# The compact agent_view renames roughly sixty keys, and that view is what MCP get_game_state
# returns by default. The mapping lives in the BuildAgent*Payload methods and nowhere else.
AGENT_BUILDER_SIGNATURE = re.compile(r"private static [^\n(]*\sBuildAgent\w*\(")
COMPACT_RENAME_HEADING = "#### compact 的字段改名对照表"
DOC_RENAME_ROW = re.compile(r"^\|[^|]*\|([^|]*)\|([^|]*)\|\s*$", re.MULTILINE)
DOC_CODE_NAME = re.compile(r"`([a-z_][a-z0-9_]*)`")
MIN_COMPACT_RENAMES = 35

HTTP_ROUTER_PATH = "STS2AIAgent/Server/Router.cs"
NATIVE_MCP_PATH = "STS2AIAgent/Server/NativeMcpServer.cs"
HEALTH_BUILDER_SIGNATURE = "internal static object BuildHealthData"
# BuildHealthData returns one anonymous object; its keys are the assignments at that object's
# indentation, which is what a client receives under "data".
HEALTH_PAYLOAD_KEY = re.compile(r"^\s{8,12}([a-z][a-z0-9_]*)\s*=", re.MULTILINE)
HEALTH_SECTION_HEADING = "## `GET /health`"
MIN_HEALTH_KEYS = 15

# A date-stamped record inside docs/ is a snapshot, not a statement about today.
DATED_DOC_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}")
HISTORICAL_MARKERS = ("历史快照", "Historical snapshot")

# Snapshots whose filename carries no date, so the pattern above cannot find them. They are
# listed explicitly to keep the marker from being quietly dropped.
REQUIRED_SNAPSHOT_MARKERS = {
    "docs/mechanic-coverage-matrix.md": "its release-candidate conclusion belongs to the v0.98.3 build it was written against",
}

# Archived topic pages keep their old path working as a redirect.
REQUIRED_REDIRECTS = {
    "docs/sts2-coverage-gaps.md": "history/sts2-coverage-gaps_2026-03-10.md",
}

# The docs/ directory used to be gitignored, so pages could be written that no fresh
# checkout (and therefore no CI run) would ever contain. Every page on disk has to be in
# the index instead. A source tarball has no .git and no index to compare against, so the
# check degrades to a printed skip there rather than inventing a failure.
DOCS_MARKDOWN_GLOB = "*.md"

# Windows PowerShell 5.1 — what `powershell` resolves to on the CI runner and on most developer
# machines — reads a BOM-less script with the machine's ANSI code page. The same bytes therefore
# decode differently per locale: the UTF-8 bytes of a dash are harmless on a GBK machine and become
# a smart closing quote on CP1252, which ends the string early and makes the whole file a parse
# error. A UTF-8 BOM removes the ambiguity, so non-ASCII PowerShell scripts have to carry one.
SCRIPT_ENCODING_GLOBS = ("scripts/*.ps1",)
UTF8_BOM = b"\xef\xbb\xbf"

# Every PowerShell script under scripts/ is a build, packaging, validation, or CI entry point and
# nothing else in the repository parses one: script-encoding only inspects BOMs, preflight compiles
# Python, and CI runs a handful by name. A stray brace or quote therefore stays invisible until a
# release or a real-machine run invokes the script, which is the worst moment to discover it. A
# parse is the cheapest static backstop; ParseFile returns the AST and error list without running
# the file, and the count is read from disk so it keeps up as scripts are added.
PS1_GLOB = "*.ps1"

# Read by the interpreter below with -Command. It reads newline-separated paths on stdin, parses
# each one with the PowerShell parser, and prints one JSON report to stdout. It deliberately uses
# single-quoted strings only so the command survives the Windows argument round-trip, and it is
# parsing only -- it never invokes, dot-sources, or -File's the scripts it reads.
PS1_PARSE_PROBE = """
$ErrorActionPreference = 'Stop'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { }
$results = [System.Collections.Generic.List[object]]::new()
foreach ($line in ([Console]::In.ReadToEnd() -split ([string][char]10))) {
    $file = $line.Trim()
    if ($file.Length -eq 0) { continue }
    $tokens = $null
    $parseErrors = $null
    [void][System.Management.Automation.Language.Parser]::ParseFile($file, [ref]$tokens, [ref]$parseErrors)
    $messages = [System.Collections.Generic.List[object]]::new()
    foreach ($parseError in $parseErrors) {
        $messages.Add([ordered]@{
            line = $parseError.Extent.StartLineNumber
            column = $parseError.Extent.StartColumnNumber
            message = $parseError.Message
        })
    }
    $results.Add([ordered]@{ file = $file; errors = $messages })
}
[Console]::Out.Write(([ordered]@{ files = $results } | ConvertTo-Json -Depth 6 -Compress))
"""


# --- packaged-links sources of truth ---------------------------------------

# package-release.ps1 rewrites the relative links in the packaged READMEs with a hand-kept
# hashtable, and check_release_package.py re-checks the result in --artifact mode. A relative
# link that is neither rewritten nor shipped only fails at packaging time, so this gate replays
# the same rewrite on the source documents and then applies the same link rules.
PACKAGE_RELEASE_SCRIPT = "scripts/package-release.ps1"
RELEASE_PACKAGE_CHECKER = "scripts/check_release_package.py"
REWRITE_FUNCTION_SIGNATURE = "function Rewrite-PackagedReadmeLinks"
# One hashtable entry inside Rewrite-PackagedReadmeLinks: "(<relative target>)" = "(<url>)".
REWRITE_ENTRY = re.compile(r'^\s*"\(([^"]+)\)"\s*=\s*"([^"]+)"\s*$', re.MULTILINE)


class GateError(Exception):
    """A verification gate failed."""


def parse_version(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for chunk in re.split(r"[.\-+]", value.strip()):
        if chunk.isdigit():
            parts.append(int(chunk))
        else:
            break
    return tuple(parts) if parts else (0,)


def version_at_least(actual: str, minimum: str) -> bool:
    left, right = list(parse_version(actual)), list(parse_version(minimum))
    width = max(len(left), len(right))
    left += [0] * (width - len(left))
    right += [0] * (width - len(right))
    return tuple(left) >= tuple(right)


def read_text(repo_root: Path, relative: str) -> str:
    path = repo_root / relative
    if not path.is_file():
        raise GateError(f"missing required file: {relative}")
    return path.read_text(encoding="utf-8")


def parse_uv_lock(text: str) -> dict[str, str]:
    packages: dict[str, str] = {}
    name: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped == "[[package]]":
            name = None
            continue
        match = re.match(r'^name = "([^"]+)"$', stripped)
        if match:
            name = match.group(1)
            continue
        match = re.match(r'^version = "([^"]+)"$', stripped)
        if match and name:
            packages.setdefault(name, match.group(1))
    return packages


def parse_pyproject_dependencies(text: str) -> list[str]:
    match = re.search(r"(?ms)^dependencies = \[(.*?)^\]", text)
    if not match:
        return []
    return re.findall(r'"([^"]+)"', match.group(1))


def dependency_name(specifier: str) -> str:
    return re.split(r"[<>=!~^\[;]", specifier, maxsplit=1)[0].strip()


def split_requirement(specifier: str) -> tuple[str, list[tuple[str, str]]]:
    """Split 'fastmcp>=3.1.0,<4.0.0' into ('fastmcp', [('>=', '3.1.0'), ('<', '4.0.0')])."""
    name = dependency_name(specifier)
    remainder = specifier[len(name):].split(";", maxsplit=1)[0]
    constraints: list[tuple[str, str]] = []
    for operator, version in re.findall(r"(~=|==|!=|<=|>=|\^|<|>)\s*([0-9][^,\s]*)", remainder):
        constraints.append((operator, version))
    return name, constraints


def satisfies(actual: str, constraints: list[tuple[str, str]]) -> bool:
    """PEP 440 subset: enough for the operators this project's manifests actually use."""
    for operator, required in constraints:
        left = parse_version(actual)
        right = parse_version(required)
        width = max(len(left), len(right))
        left += (0,) * (width - len(left))
        right += (0,) * (width - len(right))
        if operator == ">=" and not left >= right:
            return False
        if operator == ">" and not left > right:
            return False
        if operator == "<=" and not left <= right:
            return False
        if operator == "<" and not left < right:
            return False
        if operator == "==" and left != right:
            return False
        if operator == "!=" and left == right:
            return False
        if operator == "^":
            # npm caret: ^1.2.3 is >=1.2.3 and <2.0.0; ^0.2.3 is <0.3.0; ^0.0.3 pins exactly.
            if not left >= right:
                return False
            if right[0] > 0:
                upper = (right[0] + 1,)
            elif len(right) > 1 and right[1] > 0:
                upper = (0, right[1] + 1)
            else:
                return left == right
            padded = left + (0,) * max(0, len(upper) - len(left))
            if padded[: len(upper)] >= tuple(upper):
                return False
        if operator == "~=":
            # Compatible release: >= required, and the same up to the second-to-last part.
            if not left >= right:
                return False
            if len(right) >= 2 and left[: len(right) - 1] != right[: len(right) - 1]:
                return False
    return True


def flatten_overrides(overrides: dict) -> list[tuple[str, str]]:
    """npm overrides may be nested per parent package; flatten them to (package, pinned)."""
    flattened: list[tuple[str, str]] = []
    for key, value in overrides.items():
        if isinstance(value, str):
            flattened.append((key, value))
        elif isinstance(value, dict):
            flattened.extend(flatten_overrides(value))
    return flattened


def check_lockfile(repo_root: Path) -> list[str]:
    """Dependency floors and manifest/lock agreement."""
    notes: list[str] = []

    uv_lock = parse_uv_lock(read_text(repo_root, "mcp_server/uv.lock"))
    pyproject = read_text(repo_root, "mcp_server/pyproject.toml")

    for specifier in parse_pyproject_dependencies(pyproject):
        name, constraints = split_requirement(specifier)
        if not name:
            continue
        if name not in uv_lock:
            raise GateError(
                f"mcp_server/pyproject.toml declares '{name}' but mcp_server/uv.lock has no such package. "
                "Run 'uv lock' from mcp_server."
            )
        locked = uv_lock[name]
        if not satisfies(locked, constraints):
            raise GateError(
                f"mcp_server/uv.lock is out of sync with pyproject.toml: the manifest requires "
                f"'{specifier}' but the lock resolves {name} {locked}. Run 'uv lock' from mcp_server."
            )
        notes.append(f"uv.lock {name} {locked} satisfies '{specifier}'")

    for package, (minimum, advisory) in SECURITY_FLOORS.items():
        if package not in uv_lock:
            continue
        actual = uv_lock[package]
        if not version_at_least(actual, minimum):
            raise GateError(
                f"mcp_server/uv.lock pins {package} {actual}, below the safe floor {minimum} ({advisory})."
            )
        notes.append(f"uv.lock {package} {actual} >= {minimum}")

    lock_path = repo_root / "package-lock.json"
    manifest_path = repo_root / "package.json"
    if lock_path.is_file() and manifest_path.is_file():
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
        packages = lock.get("packages", {})
        for package, (minimum, advisory) in SECURITY_FLOORS.items():
            entry = packages.get(f"node_modules/{package}")
            if entry is None:
                continue
            actual = str(entry.get("version", ""))
            if not version_at_least(actual, minimum):
                raise GateError(
                    f"package-lock.json pins {package} {actual}, below the safe floor {minimum} ({advisory})."
                )
            notes.append(f"package-lock.json {package} {actual} >= {minimum}")

        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

        # The npm half of the manifest/lock agreement: every declared dependency must be
        # present in the lock at a version its range accepts.
        declared = dict(manifest.get("dependencies", {}))
        recorded = dict(packages.get("", {}).get("dependencies", {})) or dict(lock.get("dependencies", {}))
        for package, requirement in declared.items():
            if package not in recorded:
                raise GateError(
                    f"package.json declares '{package}' but package-lock.json does not record it. "
                    "Run 'npm install' from the repository root."
                )
            entry = packages.get(f"node_modules/{package}")
            if entry is None:
                raise GateError(
                    f"package.json declares '{package}' but package-lock.json has no resolved entry for it. "
                    "Run 'npm install' from the repository root."
                )
            actual = str(entry.get("version", ""))
            _, constraints = split_requirement(package + requirement)
            if not satisfies(actual, constraints):
                raise GateError(
                    f"package-lock.json is out of sync with package.json: the manifest requires "
                    f"'{package}{requirement}' but the lock resolves {actual}. "
                    "Run 'npm install' from the repository root."
                )
            notes.append(f"package-lock.json {package} {actual} satisfies '{package}{requirement}'")

        for package, pinned in flatten_overrides(manifest.get("overrides", {})):
            resolved = [
                str(entry.get("version", ""))
                for key, entry in packages.items()
                if re.search(rf"(^|/)node_modules/{re.escape(package)}$", key)
            ]
            if not resolved:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json has no such entry."
                )
            below = sorted({item for item in resolved if not version_at_least(item, pinned)})
            if below:
                raise GateError(
                    f"package.json overrides '{package}' to {pinned} but package-lock.json still resolves {', '.join(below)}."
                )
            notes.append(f"override {package} {', '.join(sorted(set(resolved)))}")
            required = REQUIRED_NPM_OVERRIDES.get(package)
            if required and required not in resolved:
                raise GateError(
                    f"the required {package} override changed: expected {required}, package-lock.json resolves {', '.join(sorted(set(resolved)))}."
                )

    return notes


def parse_code_actions(repo_root: Path) -> set[str]:
    """Action names accepted by POST /action, read from the execute switch."""
    text = read_text(repo_root, "STS2AIAgent/Game/GameActionService.cs")
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if "return actionName switch" in line:
            start = index
            break
    if start is None:
        raise GateError("could not find 'return actionName switch' in STS2AIAgent/Game/GameActionService.cs")

    actions: set[str] = set()
    for line in lines[start + 1:]:
        if re.match(r"^\s*};\s*$", line):
            break
        match = re.match(r'^\s*"([a-z][a-z0-9_]*)"\s*=>', line)
        if match:
            actions.add(match.group(1))
    if not actions:
        raise GateError("the action switch in GameActionService.cs produced no action names")
    return actions


def parse_doc_actions(repo_root: Path) -> set[str]:
    """Action names declared in the docs/api.md contract block."""
    text = read_text(repo_root, "docs/api.md")
    begin = text.find(API_CONTRACT_BEGIN)
    end = text.find(API_CONTRACT_END)
    if begin < 0 or end < 0 or end <= begin:
        raise GateError(
            f"docs/api.md is missing the '{API_CONTRACT_BEGIN}' / '{API_CONTRACT_END}' action contract block."
        )
    block = text[begin + len(API_CONTRACT_BEGIN):end]
    actions = set(re.findall(r"^-\s*`([a-z][a-z0-9_]*)`", block, re.MULTILINE))
    if not actions:
        raise GateError("the docs/api.md action contract block lists no actions")
    return actions


def check_api_doc(repo_root: Path) -> list[str]:
    code = parse_code_actions(repo_root)
    documented = parse_doc_actions(repo_root)

    missing = sorted(code - documented)
    extra = sorted(documented - code)
    problems: list[str] = []
    if missing:
        problems.append("docs/api.md does not document these actions the mod accepts: " + ", ".join(missing))
    if extra:
        problems.append("docs/api.md documents these actions the mod does not accept: " + ", ".join(extra))
    if problems:
        raise GateError(" ".join(problems))
    return [f"{len(code)} actions match between GameActionService.cs and docs/api.md"]


def slice_section(text: str, heading: str, source: str) -> str:
    """Return the text between a level-2 heading and the next level-2 heading."""
    start = text.find(heading)
    if start < 0:
        raise GateError(f"{source} no longer contains the '{heading}' section")
    rest = text[start + len(heading):]
    following = re.search(r"^## ", rest, re.MULTILINE)
    return rest[: following.start()] if following else rest


def slice_method_body(text: str, signature: str, source: str) -> str:
    """Return the brace-matched body of a method, so literals elsewhere cannot leak in."""
    start = text.find(signature)
    if start < 0:
        raise GateError(f"{source} no longer declares '{signature}'")
    opening = text.find("{", start)
    if opening < 0:
        raise GateError(f"{source}: '{signature}' has no body brace")
    depth = 0
    for index in range(opening, len(text)):
        character = text[index]
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return text[opening:index]
    raise GateError(f"{source}: '{signature}' body braces never balanced")


def read_game_state_class(repo_root: Path) -> str:
    """Every file declaring the `GameStateService` partial class, concatenated.

    A check about the class has to read the class. Reading one path made `api-facts` claim that
    `EvaluateCombatActionGate` had been deleted the moment the raw builders moved to their own
    per-screen files -- the member was fine, the reader was pointed at one file of a partial.
    """
    directory = repo_root / "STS2AIAgent" / "Game"
    files = sorted(directory.glob(GAME_STATE_CLASS_GLOB))
    if len(files) < 2:
        raise GateError(
            f"found {len(files)} file(s) matching {GAME_STATE_CLASS_GLOB} under {directory}. "
            "GameStateService is a partial class across several files on purpose; if it is being "
            "merged back, update the checks that read it instead of letting them read part of a "
            "class."
        )
    return "\n".join(path.read_text(encoding="utf-8") for path in files)


def parse_code_screens(repo_root: Path) -> set[str]:
    """Screen names GameStateService.ResolveNonModalScreen can emit."""
    text = read_game_state_class(repo_root)
    body = slice_method_body(text, RESOLVE_SCREEN_SIGNATURE, GAME_STATE_CLASS_GLOB)
    screens = set(CODE_SCREEN_SWITCH_ARM.findall(body)) | set(CODE_SCREEN_EARLY_RETURN.findall(body))
    if len(screens) < MIN_CODE_SCREENS:
        raise GateError(
            "GameStateService.ResolveNonModalScreen yielded "
            f"{len(screens)} screen names, below the {MIN_CODE_SCREENS} expected. The extraction "
            "in check_verification_gates.py no longer matches the method; fix it before trusting "
            "this gate."
        )
    return screens


def parse_doc_screens(api_doc: str) -> set[str]:
    """Screen names declared in the docs/api.md '## Screen 枚举' table."""
    section = slice_section(api_doc, SCREEN_SECTION_HEADING, "docs/api.md")
    screens = set(DOC_SCREEN_ROW.findall(section))
    if not screens:
        raise GateError(
            "the docs/api.md '## Screen 枚举' table lists no screens, so the documented screen "
            "vocabulary cannot be checked."
        )
    return screens


def slice_class_body(text: str, declaration: str, source: str) -> str:
    """Return the brace-matched body of a type declaration."""
    return slice_method_body(text, declaration, source)


def slice_doc_subsection(text: str, heading: str, source: str) -> str:
    """Return the text under a '####' heading, up to the next heading of the same or higher level."""
    start = text.find(heading)
    if start < 0:
        raise GateError(f"{source} no longer contains the '{heading}' section")
    rest = text[start + len(heading):]
    following = re.search(r"^#{1,4} ", rest, re.MULTILINE)
    return rest[: following.start()] if following else rest


def slice_doc_section(text: str, heading: str, source: str) -> str:
    """Text under a heading, up to the next heading of the same or higher level.

    Unlike :func:`slice_doc_subsection`, which stops at any heading, this keeps a section's own
    subsections. `GET /events/stream` documents its frame format under a `###` before it reaches
    the event-type table, and stopping at that subheading would have read the table as empty --
    which is a check that passes while seeing nothing.
    """
    start = text.find(heading)
    if start < 0:
        raise GateError(f"{source} no longer contains the '{heading}' section")
    level = len(heading) - len(heading.lstrip("#"))
    rest = text[start + len(heading):]
    following = re.search(r"^#{1,%d} " % level, rest, re.MULTILINE)
    return rest[: following.start()] if following else rest


def first_doc_table(section: str, heading: str) -> str:
    """Return only the first Markdown table in a section.

    A section can carry more than one table -- `combat.action_readiness` documents its fields and
    then its `reason` vocabulary -- and the field check must not read the second one's first column
    as field names.
    """
    lines = section.splitlines()
    start = next((index for index, line in enumerate(lines) if line.startswith("|")), None)
    if start is None:
        raise GateError(f"the docs/api.md '{heading}' section carries no Markdown table")
    end = start
    while end < len(lines) and lines[end].startswith("|"):
        end += 1
    return "\n".join(lines[start:end])


def parse_code_payload_fields(game_state: str, declaration: str) -> set[str]:
    """Serialized property names of a payload record, which are the JSON keys clients receive."""
    body = slice_class_body(game_state, declaration, PAYLOADS_PATH)
    fields = set(CSHARP_PAYLOAD_PROPERTY.findall(body))
    if not fields:
        raise GateError(
            f"{PAYLOADS_PATH}: '{declaration}' yielded no serialized properties. The extraction "
            "in check_verification_gates.py no longer matches the record; fix it before trusting "
            "this gate."
        )
    return fields


def parse_code_gate_reasons(game_state: str) -> set[str]:
    """Reason codes EvaluateCombatActionGate can put in combat.action_readiness.reason."""
    body = slice_method_body(game_state, COMBAT_GATE_SIGNATURE, GAME_STATE_CLASS_GLOB)
    reasons = set(CODE_GATE_REASON.findall(body))
    if len(reasons) < MIN_GATE_REASONS:
        raise GateError(
            f"EvaluateCombatActionGate yielded {len(reasons)} reason codes, below the "
            f"{MIN_GATE_REASONS} expected. The extraction in check_verification_gates.py no longer "
            "matches the method; fix it before trusting this gate."
        )
    return reasons


def check_combat_payload_docs(repo_root: Path, api_doc: str) -> list[str]:
    """The /state combat payload records and the docs/api.md tables that describe them."""
    notes: list[str] = []
    # Two files, on purpose: the records are declarations and the gate that fills them is logic.
    payloads = read_text(repo_root, PAYLOADS_PATH)
    game_state = read_game_state_class(repo_root)

    for declaration, heading in COMBAT_PAYLOAD_TABLES:
        code_fields = parse_code_payload_fields(payloads, declaration)
        section = slice_doc_subsection(api_doc, heading, "docs/api.md")
        documented = set(DOC_FIELD_ROW.findall(first_doc_table(section, heading)))
        missing = sorted(code_fields - documented)
        if missing:
            raise GateError(
                f"{declaration} serializes fields the docs/api.md '{heading}' table does not list: "
                + ", ".join(missing)
                + ". An undocumented payload field reaches every agent through the compact "
                "agent_view without anything telling clients it exists."
            )
        stale = sorted(documented - code_fields)
        if stale:
            raise GateError(
                f"the docs/api.md '{heading}' table lists fields {declaration} no longer "
                "serializes: " + ", ".join(stale) + ". Remove them so clients stop branching on a "
                "key the mod never sends."
            )
        notes.append(f"{heading}: {len(code_fields)} field(s) match {declaration}")

    code_reasons = parse_code_gate_reasons(game_state)
    reason_section = slice_doc_subsection(api_doc, DOC_REASON_SECTION, "docs/api.md")
    documented_reasons = {
        value for value in re.findall(r"\`([a-z][a-z0-9_]*)\`", reason_section)
    }
    missing_reasons = sorted(code_reasons - documented_reasons)
    if missing_reasons:
        raise GateError(
            "EvaluateCombatActionGate can answer with reason codes the docs/api.md "
            f"'{DOC_REASON_SECTION}' section never mentions: " + ", ".join(missing_reasons)
            + ". Each code tells an agent something different about whether to wait, so an "
            "undocumented one reads as an unknown failure."
        )
    notes.append(
        f"{len(code_reasons)} action_readiness reason code(s) from EvaluateCombatActionGate are "
        "documented"
    )
    return notes


def check_state_payload_coverage(repo_root: Path, api_doc: str) -> list[str]:
    """Every serialized field of every /state payload record is named somewhere in docs/api.md.

    Coarse on purpose: it does not say a field is described in the right table, only that a client
    can discover it exists at all. The per-table checks carry the precision. This net is what was
    missing when 91 fields -- whole screens, including character select, the multiplayer lobby and
    game over -- shipped with no mention anywhere a client could read.
    """
    game_state = read_text(repo_root, PAYLOADS_PATH)
    records = sorted(set(STATE_PAYLOAD_RECORD.findall(game_state)))
    if len(records) < MIN_STATE_PAYLOAD_RECORDS:
        raise GateError(
            f"{PAYLOADS_PATH} yielded {len(records)} payload records, below the "
            f"{MIN_STATE_PAYLOAD_RECORDS} expected. The extraction in check_verification_gates.py "
            "no longer matches the file; fix it before trusting this gate."
        )

    # Fenced code blocks have to go first: their fences pair with each other and would swallow the
    # inline code around them, which silently turns this check into "nothing is documented".
    prose = DOC_FENCE.sub("\n", api_doc)
    named: set[str] = set()
    for span in DOC_INLINE_CODE.findall(prose):
        for part in re.split(r"[.\[\]/ ]+", span):
            if part:
                named.add(part)

    undocumented: list[str] = []
    checked = 0
    for record in records:
        body = slice_class_body(game_state, f"internal sealed class {record}", PAYLOADS_PATH)
        fields = sorted(set(CSHARP_PAYLOAD_PROPERTY.findall(body)))
        if not fields:
            continue
        checked += len(fields)
        undocumented.extend(f"{record}.{field}" for field in fields if field not in named)

    if undocumented:
        raise GateError(
            "these /state payload fields are not named anywhere in docs/api.md: "
            + ", ".join(undocumented)
            + ". Every one of them reaches clients, and the compact agent_view carries most of them "
            "to every agent, so an undocumented field is a surface nobody can branch on."
        )
    return [
        f"{checked} field(s) across {len(records)} /state payload record(s) are named in docs/api.md"
    ]


def agent_view_builder_bodies(game_state: str) -> str:
    """The bodies of every BuildAgent*Payload method, concatenated.

    Scoping the rename check to these bodies is what keeps it honest: a compact key like `i`, `min`
    or `open` would match a loop variable or an unrelated assignment anywhere else in an 8k-line
    file.
    """
    bodies: list[str] = []
    for match in AGENT_BUILDER_SIGNATURE.finditer(game_state):
        opening = game_state.find("{", match.end())
        if opening < 0:
            continue
        depth = 0
        for index in range(opening, len(game_state)):
            if game_state[index] == "{":
                depth += 1
            elif game_state[index] == "}":
                depth -= 1
                if depth == 0:
                    bodies.append(game_state[opening:index + 1])
                    break
    return "".join(bodies)


def check_compact_rename_table(repo_root: Path, api_doc: str) -> list[str]:
    """The documented compact renames are the ones the agent view actually performs.

    The compact view is what MCP `get_game_state` returns by default, and it renames about sixty
    keys. Reading a `/state` name out of a compact payload yields undefined, so this mapping is the
    difference between an agent that can read the state and one that silently sees nothing -- and it
    was written down nowhere until this table existed.
    """
    section = slice_doc_subsection(api_doc, COMPACT_RENAME_HEADING, "docs/api.md")
    pairs: list[tuple[str, str]] = []
    for state_column, compact_column in DOC_RENAME_ROW.findall(section):
        state_names = DOC_CODE_NAME.findall(state_column)
        compact_names = DOC_CODE_NAME.findall(compact_column)
        # Rows that describe a mapping in prose rather than name-for-name are skipped on purpose;
        # the ones that do line up are pinned exactly.
        if state_names and len(state_names) == len(compact_names):
            pairs.extend(zip(state_names, compact_names))

    if len(pairs) < MIN_COMPACT_RENAMES:
        raise GateError(
            f"the docs/api.md '{COMPACT_RENAME_HEADING}' table yielded {len(pairs)} rename pairs, "
            f"below the {MIN_COMPACT_RENAMES} expected. The table or the extraction in "
            "check_verification_gates.py has changed shape; fix it before trusting this gate."
        )

    builders = agent_view_builder_bodies(read_text(repo_root, AGENT_VIEW_PATH))
    if not builders:
        raise GateError(
            f"{AGENT_VIEW_PATH} no longer declares any BuildAgent*Payload method, so the compact "
            "rename table cannot be checked."
        )

    broken = [
        f"{state} -> {compact}"
        for state, compact in pairs
        if not re.search(rf"\b{re.escape(compact)}\s*=\s*[^=;]*\b{re.escape(state)}\b", builders)
    ]
    if broken:
        raise GateError(
            "the docs/api.md compact rename table claims renames the agent view does not perform: "
            + ", ".join(broken)
            + ". A client told to read the compact key would get undefined."
        )
    return [f"{len(pairs)} compact rename(s) match the BuildAgent*Payload methods"]


def check_health_payload_docs(repo_root: Path, api_doc: str) -> list[str]:
    """Every key GET /health answers with is described in its own docs/api.md table.

    /health is the first call any client makes and the one a person is told to check when something
    is wrong, so a key that only exists in the example JSON is a key nobody knows to read.
    """
    router = read_text(repo_root, HTTP_ROUTER_PATH)
    body = slice_method_body(router, HEALTH_BUILDER_SIGNATURE, HTTP_ROUTER_PATH)
    keys = sorted(set(HEALTH_PAYLOAD_KEY.findall(body)))
    if len(keys) < MIN_HEALTH_KEYS:
        raise GateError(
            f"{HTTP_ROUTER_PATH}: BuildHealthData yielded {len(keys)} keys, below the "
            f"{MIN_HEALTH_KEYS} expected. The extraction in check_verification_gates.py no longer "
            "matches the method; fix it before trusting this gate."
        )

    section = slice_section(api_doc, HEALTH_SECTION_HEADING, "docs/api.md")
    # Only the field table counts. The example JSON above it names every key by construction, so
    # reading that too would make this check unable to fail.
    table_rows = "\n".join(line for line in section.splitlines() if line.startswith("|"))
    described = {
        name
        for cell in re.findall(r"^\|([^|]*)\|", table_rows, re.MULTILINE)
        for name in DOC_CODE_NAME.findall(cell)
    }
    missing = [key for key in keys if key not in described]
    if missing:
        raise GateError(
            "GET /health answers with keys the docs/api.md field table does not describe: "
            + ", ".join(missing)
            + ". A key that appears only in the example JSON is one no client knows to read."
        )
    return [f"{len(keys)} GET /health key(s) are described in the docs/api.md field table"]


# --- the three contract surfaces an agent reads besides the payload ---------
#
# docs/api.md describes four things a client branches on: the routes it may call, the payload
# fields it reads, the error codes it handles, and the event types it waits for. Until 2026-09-18
# only the second was checked. The other three were accurate, but by maintenance rather than by
# anything -- and a 500 `listener_error`, a 405 `method_not_allowed` and a 413 `payload_too_large`
# had already slipped out of the table, each one a response an agent can receive and cannot look up.

ERROR_CODE_HEADING = "## 错误码"
# Three ways the mod answers with an error code. The status is captured loosely because it is
# sometimes a variable (`WriteErrorAsync(response, statusCode, "not_found", ...)`), and a literal
# is the only form worth comparing against the documented column.
ERROR_EMITTERS = (
    re.compile(r'ApiException\(\s*([A-Za-z0-9_.]+)\s*,\s*"([a-z_]+)"'),
    re.compile(r'WriteErrorAsync\(\s*[^,]+,\s*([A-Za-z0-9_.]+)\s*,\s*"([a-z_]+)"'),
    re.compile(r'RestError\(\s*([A-Za-z0-9_.]+)\s*,\s*"([a-z_]+)"'),
)
ERROR_CODE_ROW = re.compile(r"^\|\s*`([a-z_]+)`[^|]*\|\s*(\d+)\s*\|", re.MULTILINE)
MIN_ERROR_CODES = 15

EVENT_SERVICE_PATH = "STS2AIAgent/Server/GameEventService.cs"
EVENT_STREAM_HEADING = "## `GET /events/stream`"
# `Publish("<name>", ...)` for the ordinary events, `BuildEnvelope("<name>", ...)` where the envelope
# is assembled first, and `PublishSnapshot("<name>", snapshot)` for the state snapshot frames. All
# three spell the event name as a literal next to the call.
EVENT_PUBLISH = re.compile(r'(?:Publish|PublishSnapshot|BuildEnvelope)\(\s*"([a-z_]+)"')
# A name reached through a constant -- `Publish(SomePolicy.EventType, ...)` -- is invisible to the
# literal pattern above, so it has to be declared here or it is checked by nobody. That is how
# `debug_churn` was added, and it is the reason this list exists instead of a comment claiming such
# names fail the gate: they did not, they were silently skipped.
EVENT_PUBLISH_CONSTANTS = {
    "debug_churn": "EventChurnPolicy.EventType",
}
EVENT_TERNARY = re.compile(r'\?\s*"([a-z_]+)"\s*:\s*"([a-z_]+)"')
EVENT_DOC_ROW = re.compile(r"^\|\s*`([a-z_]+)`(?:\s*/\s*`([a-z_]+)`)?\s*\|", re.MULTILINE)
MIN_EVENT_TYPES = 8

ROUTE_LITERAL = re.compile(r'"(/[a-z0-9/_.-]*)"')
ROUTE_DOC_HEADING = re.compile(r"^##+\s+(.*)$", re.MULTILINE)
ROUTE_IN_HEADING = re.compile(r"`(?:GET|POST|PUT|PATCH|DELETE)\s+(/[^`]*)`")
MIN_ROUTES = 8
# Not routes: fragments the router builds paths from, and paths that belong to the filesystem
# rather than to the HTTP surface.
ROUTE_LITERAL_IGNORE = {"/"}


def normalize_route(route: str) -> str:
    """A route and its documented spelling, reduced to one comparable form."""
    route = route.split("?", 1)[0]
    route = re.sub(r"\{[^}]*\}", "", route)
    route = route.rstrip("/")
    return route or "/"


def check_error_code_docs(repo_root: Path, api_doc: str) -> list[str]:
    """Every error code the mod can answer with appears in the docs/api.md table, and vice versa."""
    emitted: dict[str, set[str]] = {}
    for path in sorted((repo_root / "STS2AIAgent").rglob("*.cs")):
        if any(part in ("bin", "obj") for part in path.parts):
            continue
        text = path.read_text(encoding="utf-8")
        for pattern in ERROR_EMITTERS:
            for match in pattern.finditer(text):
                emitted.setdefault(match.group(2), set()).add(match.group(1))

    if len(emitted) < MIN_ERROR_CODES:
        raise GateError(
            f"only {len(emitted)} error code(s) were found in the mod sources, below the "
            f"{MIN_ERROR_CODES} expected. The extraction in check_verification_gates.py no longer "
            "matches how errors are raised; fix it before trusting this gate."
        )

    section = slice_doc_section(api_doc, ERROR_CODE_HEADING, "docs/api.md")
    documented: dict[str, set[str]] = {}
    for name, status in ERROR_CODE_ROW.findall(section):
        documented.setdefault(name, set()).add(status)

    undocumented = sorted(set(emitted) - set(documented))
    if undocumented:
        raise GateError(
            "the mod answers with error codes the docs/api.md table does not list: "
            + ", ".join(undocumented)
            + ". A client that receives one has nothing to look up, so it cannot tell a request it "
            "should fix from one it should retry."
        )

    phantom = sorted(set(documented) - set(emitted))
    if phantom:
        raise GateError(
            "the docs/api.md error table lists codes the mod never answers with: "
            + ", ".join(phantom)
            + ". Remove them so nobody writes a branch that can never be taken."
        )

    mismatched = []
    for name in sorted(set(emitted) & set(documented)):
        literals = {status for status in emitted[name] if status.isdigit()}
        if literals and not literals & documented[name]:
            mismatched.append(
                f"{name} (code {', '.join(sorted(literals))} vs docs {', '.join(sorted(documented[name]))})"
            )
    if mismatched:
        raise GateError(
            "these error codes are documented with the wrong HTTP status: "
            + ", ".join(mismatched)
            + ". The status is what a client branches on before it ever reads the code."
        )

    return [f"{len(emitted)} error code(s) match the docs/api.md table, status included"]


def check_event_type_docs(repo_root: Path, api_doc: str) -> list[str]:
    """Every event GET /events/stream publishes is in the documented type table, and vice versa."""
    source = read_text(repo_root, EVENT_SERVICE_PATH)
    published = set(EVENT_PUBLISH.findall(source))
    # `Publish(open ? "..._opened" : "..._closed", ...)` -- both arms are event names.
    for opened, closed in EVENT_TERNARY.findall(source):
        published.add(opened)
        published.add(closed)

    # Constant-named events, each one verified as actually published rather than merely declared:
    # an entry whose constant is no longer referenced is stale bookkeeping, not coverage.
    for event_name, constant in EVENT_PUBLISH_CONSTANTS.items():
        if constant not in source:
            raise GateError(
                f"the {event_name!r} event type is declared in this gate as published through "
                f"{constant}, but {EVENT_SERVICE_PATH} no longer mentions it. Update the gate."
            )
        published.add(event_name)

    if len(published) < MIN_EVENT_TYPES:
        raise GateError(
            f"{EVENT_SERVICE_PATH} yielded {len(published)} event type(s), below the "
            f"{MIN_EVENT_TYPES} expected. The extraction in check_verification_gates.py no longer "
            "matches the file; fix it before trusting this gate."
        )

    section = slice_doc_section(api_doc, EVENT_STREAM_HEADING, "docs/api.md")
    documented = set()
    for first, second in EVENT_DOC_ROW.findall(section):
        documented.add(first)
        if second:
            documented.add(second)

    undocumented = sorted(published - documented)
    if undocumented:
        raise GateError(
            "GET /events/stream publishes event types the docs/api.md table does not list: "
            + ", ".join(undocumented)
            + ". An agent waiting on events cannot wait for one it was never told about."
        )

    phantom = sorted(documented - published)
    if phantom:
        raise GateError(
            "the docs/api.md event table lists types the stream never publishes: "
            + ", ".join(phantom)
            + ". Waiting for one of those is waiting forever."
        )

    return [f"{len(published)} event type(s) match the docs/api.md stream table"]


def check_route_docs(repo_root: Path, api_doc: str) -> list[str]:
    """Every path the router serves has a documented endpoint section, and vice versa."""
    router = read_text(repo_root, HTTP_ROUTER_PATH)
    mcp = read_text(repo_root, NATIVE_MCP_PATH)
    served = {
        normalize_route(literal)
        for literal in ROUTE_LITERAL.findall(router) + ROUTE_LITERAL.findall(mcp)
        if literal not in ROUTE_LITERAL_IGNORE
    }
    served.discard("/")

    documented = set()
    for heading in ROUTE_DOC_HEADING.findall(api_doc):
        for route in ROUTE_IN_HEADING.findall(heading):
            documented.add(normalize_route(route))

    if len(documented) < MIN_ROUTES:
        raise GateError(
            f"docs/api.md yielded {len(documented)} endpoint heading(s), below the {MIN_ROUTES} "
            "expected. The extraction in check_verification_gates.py no longer matches the "
            "headings; fix it before trusting this gate."
        )

    undocumented = sorted(served - documented)
    if undocumented:
        raise GateError(
            "the mod serves paths docs/api.md has no endpoint section for: "
            + ", ".join(undocumented)
            + ". An endpoint nobody documents is one only its author knows how to call."
        )

    phantom = sorted(documented - served)
    if phantom:
        raise GateError(
            "docs/api.md documents endpoints the router does not serve: "
            + ", ".join(phantom)
            + ". A client following the document would get 404 not_found."
        )

    return [f"{len(served)} route(s) match the docs/api.md endpoint sections"]


def check_api_facts(repo_root: Path) -> list[str]:
    """Documented facts that a code constant owns must still agree with it."""
    notes: list[str] = []

    manifest = json.loads(read_text(repo_root, MANIFEST_VERSION_PATH))
    manifest_version = str(manifest.get("version", "")).strip()
    if not manifest_version:
        raise GateError(f"{MANIFEST_VERSION_PATH} carries no version to check docs/api.md against")

    api_doc = read_text(repo_root, "docs/api.md")

    documented_versions = MOD_VERSION_PATTERN.findall(api_doc)
    if not documented_versions:
        raise GateError(
            'docs/api.md no longer states a "mod_version" value, so the documented version '
            "cannot be checked against the manifest."
        )
    stale = sorted({value for value in documented_versions if value != manifest_version})
    if stale:
        raise GateError(
            "docs/api.md states mod_version " + ", ".join(stale) + " but " + MANIFEST_VERSION_PATH
            + " declares " + manifest_version + ". Update the docs/api.md example so it still "
            "describes the current build."
        )
    notes.append(f"docs/api.md mod_version {manifest_version} matches {MANIFEST_VERSION_PATH}")

    code_screens = parse_code_screens(repo_root)
    doc_screens = parse_doc_screens(api_doc)
    missing = sorted(code_screens - doc_screens)
    if missing:
        raise GateError(
            "GameStateService.ResolveNonModalScreen can emit screens missing from the docs/api.md "
            "'## Screen 枚举' table: " + ", ".join(missing) + ". Add them so clients can branch on "
            "the documented vocabulary."
        )
    notes.append(
        f"{len(code_screens)} screens from GameStateService.ResolveNonModalScreen all appear in "
        "the docs/api.md enum"
    )
    documented_only = sorted(doc_screens - code_screens)
    if documented_only:
        notes.append(
            "documented but not produced by ResolveNonModalScreen (expected for other producers): "
            + ", ".join(documented_only)
        )

    port_match = CODE_DEFAULT_PORT.search(read_text(repo_root, HTTP_SERVER_PATH))
    if not port_match:
        raise GateError(f"{HTTP_SERVER_PATH} no longer declares 'private const int DefaultPort = ...'")
    default_port = port_match.group(1)
    documented_ports = sorted(set(DOC_DEFAULT_PORT.findall(api_doc)))
    if not documented_ports:
        raise GateError(
            "docs/api.md no longer states the default listen port, so it cannot be checked against "
            f"{HTTP_SERVER_PATH}."
        )
    wrong_ports = sorted({port for port in documented_ports if port != default_port})
    if wrong_ports:
        raise GateError(
            "docs/api.md states default port " + ", ".join(wrong_ports) + " but " + HTTP_SERVER_PATH
            + " declares DefaultPort = " + default_port + ". Update the documented address."
        )
    notes.append(f"docs/api.md default port {default_port} matches {HTTP_SERVER_PATH} DefaultPort")

    notes.extend(check_combat_payload_docs(repo_root, api_doc))
    notes.extend(check_state_payload_coverage(repo_root, api_doc))
    notes.extend(check_compact_rename_table(repo_root, api_doc))
    notes.extend(check_health_payload_docs(repo_root, api_doc))
    notes.extend(check_error_code_docs(repo_root, api_doc))
    notes.extend(check_event_type_docs(repo_root, api_doc))
    notes.extend(check_route_docs(repo_root, api_doc))

    return notes


def check_doc_marks(repo_root: Path) -> list[str]:
    notes: list[str] = []

    for path in sorted((repo_root / "docs").rglob("*.md")):
        relative = path.relative_to(repo_root).as_posix()
        if not DATED_DOC_PATTERN.search(path.name):
            continue
        text = path.read_text(encoding="utf-8")
        if not any(marker in text for marker in HISTORICAL_MARKERS):
            raise GateError(
                f"{relative} is a date-stamped record but carries no historical marker. Add a line containing "
                "'Historical snapshot' (or the Chinese equivalent) so the file cannot be mistaken for current state."
            )
        notes.append(f"{relative} marked as a snapshot")

    for relative, reason in REQUIRED_SNAPSHOT_MARKERS.items():
        text = read_text(repo_root, relative)
        if not any(marker in text for marker in HISTORICAL_MARKERS):
            raise GateError(
                f"{relative} is a point-in-time snapshot ({reason}) but carries no historical marker. "
                "Restore the marked header so it cannot be read as current state."
            )
        notes.append(f"{relative} marked as a snapshot")

    for relative, target in REQUIRED_REDIRECTS.items():
        text = read_text(repo_root, relative)
        if target not in text:
            raise GateError(
                f"{relative} must redirect to {target} so archived topic pages keep resolving. "
                "Restore the redirect line or update REQUIRED_REDIRECTS in this script."
            )
        notes.append(f"{relative} -> {target}")

    return notes


def list_tracked_docs(repo_root: Path) -> set[str]:
    """Paths under docs/ that the git index tracks, as repo-root-relative posix strings."""
    return list_tracked_files(repo_root, "docs")


def list_tracked_files(repo_root: Path, pathspec: str) -> set[str]:
    """Paths matching a git pathspec that the index tracks, as repo-root-relative posix strings."""
    try:
        result = subprocess.run(
            # -z prints pathnames verbatim (no quoting), so non-ASCII filenames compare as-is.
            ["git", "-C", str(repo_root), "ls-files", "-z", "--", pathspec],
            capture_output=True,
            check=True,
        )
    except FileNotFoundError as exc:
        raise GateError(
            f"{repo_root} is a git work tree but 'git' could not be executed, so the "
            "tracked-file listing cannot run. Install git or run this gate from a checkout."
        ) from exc
    except subprocess.CalledProcessError as exc:
        detail = exc.stderr.decode("utf-8", "replace").strip()
        raise GateError(f"'git ls-files' failed in {repo_root}: {detail}") from exc
    return {item for item in result.stdout.decode("utf-8", "replace").split("\0") if item}


def check_docs_tracked(repo_root: Path) -> list[str]:
    """Every Markdown page under docs/ must be tracked, so none can fall out of the repo."""
    if not (repo_root / ".git").exists():
        return [
            f"{repo_root} has no .git directory, so it is not a git work tree: "
            "skipping the docs/ tracking check"
        ]

    on_disk = sorted(
        path.relative_to(repo_root).as_posix()
        for path in (repo_root / "docs").rglob(DOCS_MARKDOWN_GLOB)
        if path.is_file()
    )
    if not on_disk:
        return ["docs/ holds no Markdown files to check"]

    tracked = list_tracked_docs(repo_root)
    untracked = [relative for relative in on_disk if relative not in tracked]
    if untracked:
        raise GateError(
            "these files exist under docs/ but git does not track them: "
            + ", ".join(untracked)
            + ". docs/ is no longer gitignored, so run 'git add' on them "
            "(docs/ 已不再被忽略，请 git add) -- a fresh checkout, and therefore CI, "
            "would not contain them."
        )
    return [f"all {len(on_disk)} Markdown pages under docs/ are tracked by git"]


def load_release_package_module(repo_root: Path):
    """Import check_release_package.py so both checks share one link rule set.

    Importing (instead of re-declaring the lists and regexes) keeps this gate honest when that
    module's ARTIFACT_FILES, PACKAGED_DOCUMENTS, or link helpers change.
    """
    module_path = repo_root / RELEASE_PACKAGE_CHECKER
    if not module_path.is_file():
        raise GateError(f"missing required file: {RELEASE_PACKAGE_CHECKER}")
    spec = importlib.util.spec_from_file_location("sts2_release_package_checker", module_path)
    if spec is None or spec.loader is None:
        raise GateError(
            f"{RELEASE_PACKAGE_CHECKER} could not be imported, so its link rules cannot be reused."
        )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_packaged_link_rewrites(repo_root: Path) -> list[tuple[str, str]]:
    """The (relative target, absolute URL) pairs Rewrite-PackagedReadmeLinks replaces."""
    text = read_text(repo_root, PACKAGE_RELEASE_SCRIPT)
    body = slice_method_body(text, REWRITE_FUNCTION_SIGNATURE, PACKAGE_RELEASE_SCRIPT)
    entries = REWRITE_ENTRY.findall(body)
    if not entries:
        raise GateError(
            f'{PACKAGE_RELEASE_SCRIPT} declares no \'"(<target>)" = "(<url>)"\' replacement inside '
            "Rewrite-PackagedReadmeLinks, so the packaged-links gate cannot tell which relative "
            "links packaging rewrites. Fix the extraction in check_verification_gates.py or "
            "restore the rewrite table."
        )
    # The table stores both sides parenthesised, matching the '(<target>)' token it replaces.
    return [
        (target, url[1:-1] if url.startswith("(") and url.endswith(")") else url)
        for target, url in entries
    ]


def check_packaged_links(repo_root: Path) -> list[str]:
    """Replay the packaging rewrite on the source docs, then check every remaining local link."""
    module = load_release_package_module(repo_root)
    rewrites = parse_packaged_link_rewrites(repo_root)

    artifact_files = tuple(module.ARTIFACT_FILES)
    packaged_documents = tuple(module.PACKAGED_DOCUMENTS)
    if not artifact_files or not packaged_documents:
        raise GateError(
            f"{RELEASE_PACKAGE_CHECKER} declares no PACKAGED_DOCUMENTS or ARTIFACT_FILES, so the "
            "packaged-links gate has nothing to compare against."
        )

    notes: list[str] = []
    for document_path in packaged_documents:
        text = read_text(repo_root, document_path)
        applied = 0
        for target, url in rewrites:
            source = f"({target})"
            if source in text:
                text = text.replace(source, f"({url})")
                applied += 1

        local_links = 0
        for link in module._iter_markdown_targets(text):
            try:
                resolved = module._local_link_path(document_path, link)
            except module.PackageCheckError as exc:
                raise GateError(
                    f"{exc} A packaged document may only link to files the release ships: either add "
                    f"this link to the Rewrite-PackagedReadmeLinks table in {PACKAGE_RELEASE_SCRIPT} or "
                    "ship the target in the release artifact."
                ) from exc
            if resolved is None:
                continue
            local_links += 1
            if resolved not in artifact_files:
                raise GateError(
                    f"{document_path} links to '{link}', which resolves to '{resolved}', and that file "
                    f"is not shipped in the release artifact. Either add the link to the "
                    f"Rewrite-PackagedReadmeLinks table in {PACKAGE_RELEASE_SCRIPT} so packaging rewrites "
                    f"it to an absolute URL, or add '{resolved}' to the release artifact."
                )
        notes.append(
            f"{document_path}: {local_links} local link(s) resolve inside the artifact "
            f"({applied} rewrite rule(s) applied)"
        )
    return notes


def check_script_encoding(repo_root: Path) -> list[str]:
    notes: list[str] = []

    for pattern in SCRIPT_ENCODING_GLOBS:
        for path in sorted(repo_root.glob(pattern)):
            raw = path.read_bytes()
            relative = path.relative_to(repo_root).as_posix()
            if not any(byte > 0x7F for byte in raw):
                continue
            if not raw.startswith(UTF8_BOM):
                raise GateError(
                    f"{relative} contains non-ASCII text but has no UTF-8 BOM. Windows PowerShell 5.1 "
                    "would read it with the machine's ANSI code page, so the same bytes can decode "
                    "differently per locale and a stray quote character can break the whole script. "
                    "Save the file as UTF-8 with BOM."
                )
            notes.append(f"{relative} carries non-ASCII text with a UTF-8 BOM")

    return notes


def check_ps1_syntax(repo_root: Path) -> list[str]:
    """Every PowerShell script under scripts/ must parse without a syntax error.

    Parsing only: the interpreter is handed the file list and asked for the parser's error
    list. Nothing here executes, dot-sources, or -File's a repository script. The check
    degrades to a printed skip -- never a silent pass and never a failure -- when there is
    no .ps1 to read or no PowerShell interpreter on PATH.
    """
    scripts_dir = repo_root / "scripts"
    paths = sorted(path for path in scripts_dir.rglob(PS1_GLOB) if path.is_file())
    if not paths:
        return [f"no PowerShell scripts under {scripts_dir.name}/ to parse"]

    interpreter = shutil.which("pwsh") or shutil.which("powershell")
    if interpreter is None:
        return ["no PowerShell interpreter on PATH; skipping the PowerShell syntax check"]

    try:
        result = subprocess.run(
            [interpreter, "-NoProfile", "-NonInteractive", "-Command", PS1_PARSE_PROBE],
            input="\n".join(str(path) for path in paths).encode("utf-8"),
            capture_output=True,
        )
    except FileNotFoundError as exc:
        raise GateError(
            f"'{interpreter}' could not be executed, so the PowerShell syntax check cannot run. "
            "Install PowerShell or run this gate where an interpreter is available."
        ) from exc

    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", "replace").strip()
        raise GateError(
            "the PowerShell parser did not run (exit "
            f"{result.returncode}): {detail or 'no error output'}"
        )

    stdout = result.stdout.decode("utf-8", "replace").strip()
    try:
        report = json.loads(stdout)
    except json.JSONDecodeError as exc:
        raise GateError(
            f"the PowerShell parser produced no readable report: {stdout[:200]!r}"
        ) from exc

    # ConvertTo-Json collapses a one-element list to a bare object, so normalize before pairing.
    entries = report.get("files", [])
    if isinstance(entries, dict):
        entries = [entries]
    if len(entries) != len(paths):
        raise GateError(
            f"the PowerShell parser reported {len(entries)} files for {len(paths)} inputs, "
            "so its output cannot be trusted."
        )

    problems: list[str] = []
    for path, entry in zip(paths, entries):
        relative = path.relative_to(repo_root).as_posix()
        errors = entry.get("errors") or []
        if isinstance(errors, dict):
            errors = [errors]
        for error in errors:
            message = str(error.get("message", "")).strip()
            problems.append(
                f"{relative}:{error.get('line')}:{error.get('column')}: {message}"
            )
    if problems:
        raise GateError(
            "these PowerShell scripts have syntax errors:\n  " + "\n  ".join(problems)
        )
    return [f"{len(paths)} PowerShell scripts parse cleanly"]


SH_GLOB = "*.sh"

# Windows ships a bash that is a WSL launcher: it resolves on PATH and then disagrees with the
# filesystem about what a path is. A Git Bash install is the one that can parse these scripts, so
# the candidates are tried in order and the first that runs a trivial command wins. No candidate
# means a printed skip, which is the shape the PowerShell gate already uses.
# Git Bash first: on Windows a bare "bash" is often the WSL launcher, which resolves on PATH,
# answers a trivial command, and then cannot see a C:/ path at all. The probe below asks the real
# question -- can this interpreter read a file in this repository -- so a launcher that cannot is
# skipped rather than trusted.
BASH_CANDIDATES = (
    r"C:\Program Files\Git\bin\bash.exe",
    r"C:\Program Files (x86)\Git\bin\bash.exe",
    "bash",
)


def find_bash(repo_root: Path) -> str | None:
    probe_target = (repo_root / "scripts" / "lib-sts2-paths.sh").as_posix()
    for candidate in BASH_CANDIDATES:
        resolved = shutil.which(candidate) or (candidate if Path(candidate).is_file() else None)
        if resolved is None:
            continue
        try:
            probe = subprocess.run([resolved, "-n", probe_target], capture_output=True, timeout=60)
        except (OSError, subprocess.SubprocessError):
            continue
        if probe.returncode == 0:
            return resolved
    return None


def check_sh_syntax(repo_root: Path) -> list[str]:
    """Every bash script under scripts/ must parse, and the resolver test must pass."""
    scripts_dir = repo_root / "scripts"
    paths = sorted(path for path in scripts_dir.rglob(SH_GLOB) if path.is_file())
    if not paths:
        return [f"no bash scripts under {scripts_dir.name}/ to parse"]

    interpreter = find_bash(repo_root)
    if interpreter is None:
        return ["no usable bash on this machine; skipping the bash syntax check"]

    failures: list[str] = []
    for path in paths:
        # Forward slashes: bash reads a backslash as an escape, so a Windows path arrives mangled.
        result = subprocess.run([interpreter, "-n", path.as_posix()], capture_output=True)
        if result.returncode != 0:
            detail = result.stderr.decode("utf-8", "replace").strip()
            relative = path.relative_to(repo_root).as_posix()
            failures.append(f"{relative}: {detail or 'syntax error'}")
    if failures:
        raise GateError("these bash scripts have syntax errors:\n  " + "\n  ".join(failures))

    notes = [f"{len(paths)} bash scripts parse cleanly"]

    test_path = scripts_dir / "test-lib-sts2-paths.sh"
    if not test_path.is_file():
        raise GateError(
            "scripts/test-lib-sts2-paths.sh is missing, so the path resolver has no offline "
            "coverage left. Restore it, or record where that coverage moved."
        )

    result = subprocess.run(
        [interpreter, test_path.as_posix()], capture_output=True, cwd=str(repo_root)
    )
    if result.returncode != 0:
        stdout = result.stdout.decode("utf-8", "replace").strip()
        detail = result.stderr.decode("utf-8", "replace").strip()
        raise GateError("the offline path-resolver test failed:\n" + stdout + "\n" + detail)
    summary = result.stdout.decode("utf-8", "replace").strip().splitlines()
    notes.append("resolver test: " + (summary[-1] if summary else "passed"))
    return notes


ARCH_SPEC_PATH = ".trellis/spec/mod/architecture.md"
ARCH_TABLE_HEADING = "## Code shape and its known debts"
# The size ratchet's default budget. A file past it is a file the architecture page has to name,
# because "which files are big" is the one thing that page exists to answer.
ARCH_LISTED_FLOOR = 1000
# Line counts drift a few lines at a time and re-measuring on every commit would be a tax nobody
# pays for long. 5% is wide enough that ordinary work never touches this gate and narrow enough
# that a refactor cannot hide: the table sat at 8,559 for GameStateService.cs while the file was
# 5,872, which is 46% out.
ARCH_LINE_TOLERANCE = 0.05
ARCH_FILE_ROW = re.compile(r"^\|\s*\[([^\]]+)\]\(([^)]+)\)\s*\|\s*([\d,]+)\s*\|", re.MULTILINE)
ARCH_TOTALS = re.compile(
    r"across\s+([\d,]+)\s+mod source files totalling\s+([\d,]+)\s+lines", re.MULTILINE
)


def count_lines(path: Path) -> int:
    """Lines as `wc -l` counts them, which is what the size budgets and the table both mean."""
    return path.read_text(encoding="utf-8").count("\n")


def mod_source_files(repo_root: Path) -> list[Path]:
    """Every mod source file git tracks, skipping generated build output.

    Tracked, not on disk. A working tree also holds whatever the developer left there --
    STS2AIAgent/_scratch/ is gitignored and real -- so counting files by walking the directory
    measures one machine rather than the repository, and CI would count something different.
    """
    mod_root = repo_root / "STS2AIAgent"
    if not (repo_root / ".git").exists():
        # A source tarball has no index; fall back to the tree and say so through the caller.
        candidates = mod_root.rglob("*.cs")
    else:
        candidates = (
            repo_root / relative
            for relative in list_tracked_files(repo_root, "STS2AIAgent/*.cs")
        )
    return sorted(
        path
        for path in candidates
        if path.is_file()
        and not any(part in ("bin", "obj") for part in path.relative_to(mod_root).parts)
    )


def within_tolerance(stated: int, actual: int) -> bool:
    return abs(stated - actual) <= max(1, round(actual * ARCH_LINE_TOLERANCE))


def check_arch_facts(repo_root: Path) -> list[str]:
    """The architecture page's measurements against the files it measures.

    A page that says where the weight is, and is wrong about it, is worse than no page: it sends
    the next person to the wrong file and tells them the shape of the code is something it is not.
    This one went stale once already -- it carried pre-ADR-0001 numbers and told readers to add
    every new action to *both* action surfaces for a month after that duplication was gone.
    """
    spec = read_text(repo_root, ARCH_SPEC_PATH)
    if ARCH_TABLE_HEADING not in spec:
        raise GateError(
            f"{ARCH_SPEC_PATH} has no '{ARCH_TABLE_HEADING}' section. That section is where this "
            "gate reads the measurements; renaming it silently turns the check off."
        )

    section = spec[spec.index(ARCH_TABLE_HEADING):]
    rows = ARCH_FILE_ROW.findall(section)
    if len(rows) < 3:
        raise GateError(
            f"{ARCH_SPEC_PATH}: the file table yielded {len(rows)} row(s). The table or the "
            "extraction in check_verification_gates.py has changed shape; fix it before trusting "
            "this gate."
        )

    notes: list[str] = []
    listed: set[str] = set()
    for name, link, stated_text in rows:
        target = (repo_root / ".trellis" / "spec" / "mod" / link).resolve()
        if not target.is_file():
            raise GateError(
                f"{ARCH_SPEC_PATH} lists {name}, but {link} resolves to no file. Either the file "
                "moved and the row was left behind, or the link is wrong -- both send a reader "
                "somewhere the code is not."
            )
        try:
            relative = target.relative_to(repo_root.resolve()).as_posix()
        except ValueError:
            raise GateError(
                f"{ARCH_SPEC_PATH} lists {name} at {link}, which resolves outside the repository."
            ) from None
        listed.add(relative)

        stated = int(stated_text.replace(",", ""))
        actual = count_lines(target)
        if not within_tolerance(stated, actual):
            raise GateError(
                f"{ARCH_SPEC_PATH} says {relative} is {stated:,} lines; it is {actual:,}. "
                "Re-measure the table. A page that is wrong about where the weight is sends the "
                "next person to the wrong file."
            )
        notes.append(f"{relative}: {actual:,} lines, table says {stated:,}")

    sources = mod_source_files(repo_root)
    total_lines = sum(count_lines(path) for path in sources)
    totals = ARCH_TOTALS.search(section)
    if not totals:
        raise GateError(
            f"{ARCH_SPEC_PATH} no longer states how many mod source files it measured and how many "
            "lines they hold. That sentence is what makes the table's shares meaningful."
        )
    stated_files = int(totals.group(1).replace(",", ""))
    stated_total = int(totals.group(2).replace(",", ""))
    if not within_tolerance(stated_files, len(sources)):
        raise GateError(
            f"{ARCH_SPEC_PATH} says the mod has {stated_files} source files; it has {len(sources)}."
        )
    if not within_tolerance(stated_total, total_lines):
        raise GateError(
            f"{ARCH_SPEC_PATH} says the mod totals {stated_total:,} lines; it totals "
            f"{total_lines:,}. Re-measure."
        )
    notes.append(f"{len(sources)} mod source files totalling {total_lines:,} lines")

    unlisted = sorted(
        path.relative_to(repo_root).as_posix()
        for path in sources
        if count_lines(path) > ARCH_LISTED_FLOOR
        and path.relative_to(repo_root).as_posix() not in listed
    )
    if unlisted:
        raise GateError(
            f"these files are over {ARCH_LISTED_FLOOR:,} lines and {ARCH_SPEC_PATH} does not name "
            "them: " + ", ".join(unlisted) + ". The table is how someone finds out where the mod's "
            "weight is; a monolith it omits is one nobody is watching."
        )
    notes.append(
        f"every file over {ARCH_LISTED_FLOOR:,} lines appears in the table ({len(listed)} listed)"
    )
    return notes


DOC_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
DOC_FENCE = re.compile(r"```.*?```", re.DOTALL)
# Paths whose Markdown is not this repository's prose: vendored trees and the template backup
# Trellis keeps, which deliberately holds an older copy of pages that have since moved.
DOC_LINK_SKIP = ("node_modules/", ".trellis/.backup")
# The floor is proportional, not absolute. Its job is to catch an extraction that has
# stopped matching -- the failure mode where a regex quietly returns nothing and the
# gate reports success over zero links. An absolute number would also have meant the
# gate could only ever run against a tree this size, which is not true of the fixture
# the self-test builds. A page carries roughly one link here, so a quarter of that is
# far below any healthy tree and far above a broken extraction.
MIN_DOC_LINKS_PER_PAGE = 4
# A link may not carry a "#L123" or "#L10-L20" anchor. Those rot the moment the file is edited,
# and silently: the link still resolves, it just lands somewhere else. This gate first rejected
# only anchors past the end of the file -- which caught six when client.py and server.py were
# split -- but an anchor inside the file is no safer, only harder to catch: when the forty-one
# anchors in the specs were replaced on 2026-09-18, one that read "build_parser" pointed into the
# middle of another function and three test links landed on blank lines. A symbol name is
# searchable forever; a line number is right for one commit.
DOC_LINE_ANCHOR = re.compile(r"^L(\d+)(?:-L(\d+))?$")


def check_doc_links(repo_root: Path) -> list[str]:
    """Every relative Markdown link in a tracked page resolves to something in the repo.

    `packaged-links` answers a narrower question -- whether the three documents shipped inside the
    release artifact still resolve once they are out of the repository. This one covers the other
    four hundred pages, where a link breaks for the dullest reason there is: a file moved and the
    pages that pointed at it did not. Nothing was checking, and a specification that sends a reader
    to a 404 is how a document stops being trusted and then stops being read.
    """
    if not (repo_root / ".git").exists():
        return [
            f"{repo_root} has no .git directory, so it is not a git work tree: "
            "skipping the Markdown link check"
        ]

    pages = [
        relative
        for relative in list_tracked_files(repo_root, "*.md")
        if not relative.startswith(DOC_LINK_SKIP)
    ]
    if not pages:
        return ["no tracked Markdown pages to check"]

    tracked = list_tracked_files(repo_root, ".")
    broken: list[str] = []
    dangling_anchors: list[str] = []
    checked = 0
    for relative in pages:
        path = repo_root / relative
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for target in DOC_LINK.findall(DOC_FENCE.sub("", text)):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            # Strip the anchor and any query: this gate answers "does the file exist", and a
            # heading anchor is not a file. Percent-escapes are undone so a link written with
            # %20 for a space resolves the way a reader's browser would resolve it.
            file_part, _, anchor = target.partition("#")
            cleaned = unquote(file_part.split("?", 1)[0])
            if not cleaned:
                continue
            checked += 1
            resolved = (path.parent / cleaned).resolve()
            try:
                target_relative = resolved.relative_to(repo_root.resolve()).as_posix()
            except ValueError:
                broken.append(f"{relative} -> {target} (outside the repository)")
                continue
            # Tracked, not merely present. This gate exists to answer "will a reader who clones
            # this repository be able to follow the link", and the working tree holds files a
            # clone does not: AGENTS.md and extraction/decompiled/ are both gitignored and both
            # real on a developer's disk. Asking the filesystem made the answer depend on whose
            # machine ran the gate -- it passed locally and failed on CI, which is the whole
            # failure mode this gate was added to prevent, one level up.
            target_prefix = target_relative.rstrip("/") + "/"
            target_is_tracked = (
                target_relative == "."
                or target_relative in tracked
                or any(item.startswith(target_prefix) for item in tracked)
            )
            if not target_is_tracked:
                broken.append(f"{relative} -> {target}")
                continue

            line_anchor = DOC_LINE_ANCHOR.match(anchor)
            if line_anchor:
                note = ""
                if resolved.is_file():
                    wanted = int(line_anchor.group(2) or line_anchor.group(1))
                    available = resolved.read_text(encoding="utf-8", errors="replace").count("\n") + 1
                    if wanted > available:
                        note = f" ({Path(cleaned).name} has {available} lines)"
                dangling_anchors.append(f"{relative} -> {target}{note}")

    floor = max(1, len(pages) // MIN_DOC_LINKS_PER_PAGE)
    if checked < floor:
        raise GateError(
            f"only {checked} relative Markdown link(s) were found across {len(pages)} tracked "
            f"pages, below the {floor} expected. The extraction in check_verification_gates.py "
            "has stopped matching the pages; fix it before trusting this gate."
        )
    if broken:
        raise GateError(
            "these Markdown links point at files that are not in the repository: "
            + ", ".join(broken)
            + ". A link usually breaks because the target moved, so check where the file went "
            "rather than deleting the link."
        )
    if dangling_anchors:
        raise GateError(
            "these Markdown links point at a line number: "
            + ", ".join(dangling_anchors)
            + ". A line anchor rots as soon as the file is edited, and it rots quietly -- the link "
            "still opens, it just lands somewhere else. Link the file and name the symbol instead "
            "(a function, class, step name or parameter), which stays findable by search."
        )

    return [f"{checked} relative link(s) across {len(pages)} tracked Markdown pages resolve"]


def check_api_schema(repo_root: Path) -> list[str]:
    """The committed machine-readable API contract is the generator's exact output.

    The deep generator owns parsing and type mapping rather than duplicating them beside this
    dispatcher. Import by file path so the check also works in the throwaway fixture used by the
    gate self-test, whose scripts/ directory is intentionally not a Python package.
    """
    module_path = repo_root / "scripts" / "api_schema.py"
    if not module_path.is_file():
        raise GateError("scripts/api_schema.py is missing, so docs/openapi.json cannot be verified")
    spec = importlib.util.spec_from_file_location("sts2_api_schema", module_path)
    if spec is None or spec.loader is None:
        raise GateError("scripts/api_schema.py could not be imported, so docs/openapi.json cannot be verified")
    module = importlib.util.module_from_spec(spec)
    try:
        # dataclasses resolves annotations through sys.modules while this module is executing.
        # Register it first, as normal Python import machinery does.
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module.check_spec(repo_root)
    except Exception as exc:
        detail = str(exc).strip() or type(exc).__name__
        raise GateError(detail) from exc
    finally:
        sys.modules.pop(spec.name, None)


GATES = {
    "lockfile": check_lockfile,
    "api-doc": check_api_doc,
    "api-facts": check_api_facts,
    "api-schema": check_api_schema,
    "doc-marks": check_doc_marks,
    "docs-tracked": check_docs_tracked,
    "doc-links": check_doc_links,
    "arch-facts": check_arch_facts,
    "packaged-links": check_packaged_links,
    "script-encoding": check_script_encoding,
    "ps1-syntax": check_ps1_syntax,
    "sh-syntax": check_sh_syntax,
}


def use_utf8_streams() -> None:
    """Make the gate's own output survive a console that is not UTF-8.

    Gate messages quote what they check, and what they check includes Chinese section headings from
    docs/api.md. On the Windows CI runner stdout defaults to cp1252, where printing one of those
    raises UnicodeEncodeError -- so a gate that passed still exited 1, and, worse, a gate that failed
    would have had its real message replaced by an encoding traceback. Writing UTF-8 bytes keeps the
    heading readable in the CI log viewer; `errors="replace"` means no console can ever turn a
    verification result into a crash.
    """
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        try:
            reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):
            # A stream that refuses to be reconfigured (a pipe already in text mode on an exotic
            # host) is not worth failing the run over; the gates themselves are unaffected.
            pass


def main() -> int:
    use_utf8_streams()
    parser = argparse.ArgumentParser(description="Run the offline verification gates.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--only", choices=sorted(GATES), action="append", help="run only the named gate(s)")
    parser.add_argument(
        "--skip",
        choices=sorted(GATES),
        action="append",
        help="run every gate except the named one(s); for a tree a gate cannot meaningfully "
        "measure, such as the self-test's partial fixture against doc-links",
    )
    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()
    missing = [name for name in ROOT_SENTINELS if not (repo_root / name).is_file()]
    if missing:
        print(
            f"verification gates failed: {repo_root} does not look like the repository root "
            f"(missing {', '.join(missing)})",
            file=sys.stderr,
        )
        return 1

    selected = [name for name in (args.only or sorted(GATES)) if name not in set(args.skip or ())]
    if not selected:
        print("verification gates failed: every gate was skipped", file=sys.stderr)
        return 1
    try:
        for name in selected:
            notes = GATES[name](repo_root)
            print(f"[gate] {name}: ok")
            for note in notes:
                print(f"  - {note}")
    except GateError as exc:
        print(f"verification gates failed ({name}): {exc}", file=sys.stderr)
        return 1

    print(f"verification gates passed: {', '.join(selected)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
